# Generated by Django 6.0.6 on 2026-06-07 16:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=15)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=50)),
                ('capacidad_kg', models.DecimalField(decimal_places=2, max_digits=7)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('Planificacion', 'En Planificación'), ('En_Transito', 'En Tránsito'), ('Completada', 'Completada')], default='Planificacion', max_length=20)),
                ('distancia_total_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tiempo_estimado_min', models.IntegerField(blank=True, null=True)),
                ('geometria_ruta', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('repartidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='envios.repartidor')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='envios.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_seguimiento', models.CharField(max_length=20, unique=True)),
                ('referencia_externa_id', models.CharField(max_length=100)),
                ('direccion_destino', models.CharField(max_length=255)),
                ('latitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('orden_parada', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Bodega', 'En Bodega'), ('Asignado', 'Asignado a Ruta'), ('En_Camino', 'En Camino'), ('Entregado', 'Entregado'), ('Fallido', 'Intento Fallido')], default='Bodega', max_length=20)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paradas', to='envios.ruta')),
            ],
        ),
    ]
