# Generated by Django 6.0.6 on 2026-06-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='costo_final',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='envio',
            name='requiere_instalacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='envio',
            name='valor_base_producto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='costo_por_hora',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='costo_por_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tarifa_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo_vehiculo',
            field=models.CharField(choices=[('moto', 'Motocicleta (Carga Ligera / Express)'), ('furgon_ligero', 'Furgón Ligero (Carga Menor)'), ('furgon_mediano', 'Furgón de Carga Mediana (Última Milla)'), ('camion_urbano', 'Camión de Reparto Urbano (Carga Pesada / Voluminosa)')], default='moto', max_length=20),
        ),
    ]
