# Generated by Django 6.0.6 on 2026-06-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0002_envio_costo_final_envio_requiere_instalacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='comuna',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_vehiculo',
            field=models.CharField(choices=[('moto', 'Motocicleta (Carga Ligera / Express)'), ('furgon_ligero', 'Furgón Ligero (Carga Menor)'), ('furgon_mediano', 'Furgón de Carga Mediana (Carga Mediana)'), ('camion_urbano', 'Camión de Reparto  (Carga Pesada / Voluminosa)')], default='moto', max_length=20),
        ),
    ]
